- project:
    templates:
      - openstack-python-jobs
      - openstack-python3-ussuri-jobs
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-lower-constraints-jobs
      - release-notes-jobs-python3
